using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace VS_CRM.Models.DATA_DB_Model
{
    public partial class ЗОценки
    {
        public int Hid { get; set; }
        public int Год { get; set; }
        public decimal КМво01 { get; set; }
        public decimal Оклад01 { get; set; }
        public decimal Бонус01 { get; set; }
        public decimal КИнд101 { get; set; }
        public decimal КИнд201 { get; set; }
        public decimal Доплаты01 { get; set; }
        public decimal Стаж01 { get; set; }
        public decimal Выслуга01 { get; set; }
        public int? ДнПл01 { get; set; }
        public int? ДнФк01 { get; set; }
        public decimal КМво02 { get; set; }
        public decimal Оклад02 { get; set; }
        public decimal Бонус02 { get; set; }
        public decimal КИнд102 { get; set; }
        public decimal КИнд202 { get; set; }
        public decimal Доплаты02 { get; set; }
        public decimal Стаж02 { get; set; }
        public decimal Выслуга02 { get; set; }
        public int? ДнПл02 { get; set; }
        public int? ДнФк02 { get; set; }
        public decimal КМво03 { get; set; }
        public decimal Оклад03 { get; set; }
        public decimal Бонус03 { get; set; }
        public decimal КИнд103 { get; set; }
        public decimal КИнд203 { get; set; }
        public decimal Доплаты03 { get; set; }
        public decimal Стаж03 { get; set; }
        public decimal Выслуга03 { get; set; }
        public int? ДнПл03 { get; set; }
        public int? ДнФк03 { get; set; }
        public decimal КМво04 { get; set; }
        public decimal Оклад04 { get; set; }
        public decimal Бонус04 { get; set; }
        public decimal КИнд104 { get; set; }
        public decimal КИнд204 { get; set; }
        public decimal Доплаты04 { get; set; }
        public decimal Стаж04 { get; set; }
        public decimal Выслуга04 { get; set; }
        public int? ДнПл04 { get; set; }
        public int? ДнФк04 { get; set; }
        public decimal КМво05 { get; set; }
        public decimal Оклад05 { get; set; }
        public decimal Бонус05 { get; set; }
        public decimal КИнд105 { get; set; }
        public decimal КИнд205 { get; set; }
        public decimal Доплаты05 { get; set; }
        public decimal Стаж05 { get; set; }
        public decimal Выслуга05 { get; set; }
        public int? ДнПл05 { get; set; }
        public int? ДнФк05 { get; set; }
        public decimal КМво06 { get; set; }
        public decimal Оклад06 { get; set; }
        public decimal Бонус06 { get; set; }
        public decimal КИнд106 { get; set; }
        public decimal КИнд206 { get; set; }
        public decimal Доплаты06 { get; set; }
        public decimal Стаж06 { get; set; }
        public decimal Выслуга06 { get; set; }
        public int? ДнПл06 { get; set; }
        public int? ДнФк06 { get; set; }
        public decimal КМво07 { get; set; }
        public decimal Оклад07 { get; set; }
        public decimal Бонус07 { get; set; }
        public decimal КИнд107 { get; set; }
        public decimal КИнд207 { get; set; }
        public decimal Доплаты07 { get; set; }
        public decimal Стаж07 { get; set; }
        public decimal Выслуга07 { get; set; }
        public int? ДнПл07 { get; set; }
        public int? ДнФк07 { get; set; }
        public decimal КМво08 { get; set; }
        public decimal Оклад08 { get; set; }
        public decimal Бонус08 { get; set; }
        public decimal КИнд108 { get; set; }
        public decimal КИнд208 { get; set; }
        public decimal Доплаты08 { get; set; }
        public decimal Стаж08 { get; set; }
        public decimal Выслуга08 { get; set; }
        public int? ДнПл08 { get; set; }
        public int? ДнФк08 { get; set; }
        public decimal КМво09 { get; set; }
        public decimal Оклад09 { get; set; }
        public decimal Бонус09 { get; set; }
        public decimal КИнд109 { get; set; }
        public decimal КИнд209 { get; set; }
        public decimal Доплаты09 { get; set; }
        public decimal Выслуга09 { get; set; }
        public int? ДнПл09 { get; set; }
        public int? ДнФк09 { get; set; }
        public decimal Стаж09 { get; set; }
        public decimal КМво10 { get; set; }
        public decimal Оклад10 { get; set; }
        public decimal Бонус10 { get; set; }
        public decimal КИнд110 { get; set; }
        public decimal КИнд210 { get; set; }
        public decimal Доплаты10 { get; set; }
        public decimal Стаж10 { get; set; }
        public decimal Выслуга10 { get; set; }
        public int? ДнПл10 { get; set; }
        public int? ДнФк10 { get; set; }
        public decimal КМво11 { get; set; }
        public decimal Оклад11 { get; set; }
        public decimal Бонус11 { get; set; }
        public decimal КИнд111 { get; set; }
        public decimal КИнд211 { get; set; }
        public decimal Доплаты11 { get; set; }
        public decimal Стаж11 { get; set; }
        public decimal Выслуга11 { get; set; }
        public int? ДнПл11 { get; set; }
        public int? ДнФк11 { get; set; }
        public decimal КМво12 { get; set; }
        public decimal Оклад12 { get; set; }
        public decimal Бонус12 { get; set; }
        public decimal КИнд112 { get; set; }
        public decimal КИнд212 { get; set; }
        public decimal Доплаты12 { get; set; }
        public decimal Стаж12 { get; set; }
        public decimal Выслуга12 { get; set; }
        public int? ДнПл12 { get; set; }
        public int? ДнФк12 { get; set; }
        public decimal? Опоздания01 { get; set; }
        public int? Опоздания01Мин { get; set; }
        public decimal? Опоздания02 { get; set; }
        public int? Опоздания02Мин { get; set; }
        public decimal? Опоздания03 { get; set; }
        public int? Опоздания03Мин { get; set; }
        public decimal? Опоздания04 { get; set; }
        public int? Опоздания04Мин { get; set; }
        public decimal? Опоздания05 { get; set; }
        public int? Опоздания05Мин { get; set; }
        public decimal? Опоздания06 { get; set; }
        public int? Опоздания06Мин { get; set; }
        public int? Опоздания07Мин { get; set; }
        public decimal? Опоздания07 { get; set; }
        public int? Опоздания08Мин { get; set; }
        public decimal? Опоздания08 { get; set; }
        public int? Опоздания09Мин { get; set; }
        public decimal? Опоздания09 { get; set; }
        public int? Опоздания10Мин { get; set; }
        public decimal? Опоздания10 { get; set; }
        public int? Опоздания11Мин { get; set; }
        public decimal? Опоздания11 { get; set; }
        public int? Опоздания12Мин { get; set; }
        public decimal? Опоздания12 { get; set; }
        public int? Утв01 { get; set; }
        public int? Утв02 { get; set; }
        public int? Утв03 { get; set; }
        public int? Утв04 { get; set; }
        public int? Утв05 { get; set; }
        public int? Утв06 { get; set; }
        public int? Утв07 { get; set; }
        public int? Утв08 { get; set; }
        public int? Утв09 { get; set; }
        public int? Утв10 { get; set; }
        public int? Утв11 { get; set; }
        public int? Утв12 { get; set; }
        public decimal? Премия101 { get; set; }
        public decimal? Премия201 { get; set; }
        public decimal? Премия102 { get; set; }
        public decimal? Премия202 { get; set; }
        public decimal? Премия103 { get; set; }
        public decimal? Премия203 { get; set; }
        public decimal? Премия104 { get; set; }
        public decimal? Премия204 { get; set; }
        public decimal? Премия105 { get; set; }
        public decimal? Премия205 { get; set; }
        public decimal? Премия106 { get; set; }
        public decimal? Премия206 { get; set; }
        public decimal? Премия107 { get; set; }
        public decimal? Премия207 { get; set; }
        public decimal? Премия108 { get; set; }
        public decimal? Премия208 { get; set; }
        public decimal? Премия109 { get; set; }
        public decimal? Премия209 { get; set; }
        public decimal? Премия110 { get; set; }
        public decimal? Премия210 { get; set; }
        public decimal? Премия111 { get; set; }
        public decimal? Премия211 { get; set; }
        public decimal? Премия112 { get; set; }
        public decimal? Премия212 { get; set; }
        public decimal NmcПроц01 { get; set; }
        public decimal NmcПроц02 { get; set; }
        public decimal NmcПроц03 { get; set; }
        public decimal NmcПроц04 { get; set; }
        public decimal NmcПроц05 { get; set; }
        public decimal NmcПроц06 { get; set; }
        public decimal NmcПроц07 { get; set; }
        public decimal NmcПроц08 { get; set; }
        public decimal NmcПроц09 { get; set; }
        public decimal NmcПроц10 { get; set; }
        public decimal NmcПроц11 { get; set; }
        public decimal NmcПроц12 { get; set; }
        public decimal? NmcПроцДв01 { get; set; }
        public decimal? NmcПроцДв02 { get; set; }
        public decimal? NmcПроцДв03 { get; set; }
        public decimal? NmcПроцДв04 { get; set; }
        public decimal? NmcПроцДв05 { get; set; }
        public decimal? NmcПроцДв06 { get; set; }
        public decimal? NmcПроцДв07 { get; set; }
        public decimal? NmcПроцДв08 { get; set; }
        public decimal? NmcПроцДв09 { get; set; }
        public decimal? NmcПроцДв10 { get; set; }
        public decimal? NmcПроцДв11 { get; set; }
        public decimal? NmcПроцДв12 { get; set; }
    }
}
